// Auto-generated by scripts/generate_assets_manifest.py
window.TOP2PANO_ASSETS = {
  "objects": [
    {
      "id": "bed",
      "label": "Bed",
      "src": "img/assets/bed.png",
      "defaultWidth": 254,
      "defaultHeight": 258
    },
    {
      "id": "chair",
      "label": "Chair",
      "src": "img/assets/chair.png",
      "defaultWidth": 80,
      "defaultHeight": 92
    },
    {
      "id": "countertop",
      "label": "Countertop",
      "src": "img/assets/countertop.png",
      "defaultWidth": 240,
      "defaultHeight": 70
    },
    {
      "id": "fridge",
      "label": "Fridge",
      "src": "img/assets/fridge.png",
      "defaultWidth": 48,
      "defaultHeight": 42
    },
    {
      "id": "sink",
      "label": "Sink",
      "src": "img/assets/sink.png",
      "defaultWidth": 54,
      "defaultHeight": 84
    },
    {
      "id": "sofa",
      "label": "Sofa",
      "src": "img/assets/sofa.png",
      "defaultWidth": 268,
      "defaultHeight": 120
    },
    {
      "id": "table",
      "label": "Table",
      "src": "img/assets/table.png",
      "defaultWidth": 92,
      "defaultHeight": 98
    },
    {
      "id": "toilet",
      "label": "Toilet",
      "src": "img/assets/toilet.png",
      "defaultWidth": 44,
      "defaultHeight": 62
    },
    {
      "id": "tvstand",
      "label": "Tvstand",
      "src": "img/assets/tvstand.png",
      "defaultWidth": 240,
      "defaultHeight": 70
    }
  ],
  "textures": [
    {
      "id": "tex_bath",
      "label": "tex_bath",
      "src": "img/assets/tex_bath.png",
      "tileSize": 50
    },
    {
      "id": "tex_tile",
      "label": "tex_tile",
      "src": "img/assets/tex_tile.png",
      "tileSize": 48
    },
    {
      "id": "tex_wood",
      "label": "tex_wood",
      "src": "img/assets/tex_wood.png",
      "tileSize": 68
    }
  ]
};
